Make it build with ghc-9.8
haskellari/splitmix pull request #77
Opened 2023-08-31 06:28 UTC by erikd

2023-08-31 06:30 UTC, erikd commented on tests/TestU01.hs
> -    | otherwise                   = fmap2 (Ap Arg) (singleArg p x xs)
The `head` function now gives a "partial function" warning, so replace it with something total.

2023-08-31 09:55 UTC, phadej requested changes
This is bounds only change. I'll do it when there are release candidate. (The GHC alphas bundle libraries with incorrect version metadata).

2023-08-31 09:55 UTC, phadej commented on cabal.project
> +allow-newer: stm-2.5.1.0:base
These don't look right. `stm`, `primitive`, `async:hashable` stuff shouldn't be required. But `async:base` does.

2023-09-25 10:20 UTC, Kleidukos commented
@phadej Does 9.8.0.20230919 still ship with incorrect library metadata?

2023-09-25 10:25 UTC, phadej commented
> Does 9.8.0.20230919 still ship with incorrect library metadata?

Yes.

2023-10-03 18:23 UTC, closed without merging